#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -D_DARWIN_C_SOURCE -UOPENSSL_BN_ASM_PART_WORDS -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk -Wno-unused-value -Wno-parentheses"
  #define PLATFORM "darwin-i386-cc"
  #define DATE "Thu Apr 17 14:16:47 PKT 2014"
#endif
